#:schema node_modules/wrangler/config-schema.json
name = "nuxt-comments-app"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "nuxt-comments"
database_id = "d0c4f4b9-f506-47b3-9afa-a20c5d4336d9"